version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"

  prometheus:
    image: "prom/prometheus"
    volumes:
      - "$PWD/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  gateway:
    image: "prom/pushgateway"
    ports:
      - "9091:9091"