global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - localhost:9090
 - job_name: hello-prom
   static_configs:
    - targets:
       - midgard.local:8000
 - job_name: hello-gw
   static_configs:
    - targets:
       - midgard.local:9091